#version 450
#extension GL_KHR_vulkan_glsl: enable

layout( local_size_x = 32, local_size_y = 32 ) in;

layout( set = 0, binding = 0) uniform sampler2D render_target;
layout( set = 0, binding = 1) writeonly uniform image2D luminance_tex;

void main() {
    float lum = dot( texelFetch( render_target, ivec2(gl_GlobalInvocationID.xy), 0 ).xyz, vec3(0.2126f, 0.7152f, 0.0722f) );
    imageStore(luminance_tex, ivec2(gl_GlobalInvocationID.xy), vec4(log( lum + 0.00001f ))); 
}